### ISSUE TITLE
[Feature request] Document how to customize commonmarker settings

### ISSUE THREAD

**Issue by jstolarek** [gollum/gollum#1651]
The wiki currently documents how to set custom options for kramdown - see [here](https://github.com/gollum/gollum/wiki/Custom-rendering-gems#changing-github-markups-default-rendering-settings). Would it be possible to document how to use custom rendering and parsing options for `commonmarker`? I want to enable footnotes in my wiki, which requires setting a custom `commonmarker` option (documented [here](https://github.com/gjtorikian/commonmarker#parse-options)), but I can't figure out how to do that.

**Comment by dometto** [comment]
Done. In case I made a mistake in creating the example, please feel free to edit it -- the wiki is publicly editable. But this should make clear what the right approach is.

**Comment by bartkamphorst** [comment]
That's great, @dometto, thanks. For reference, could you link to the wiki page with the info here in this issue?

**Comment by dometto** [comment]
Info is here:
https://github.com/gollum/gollum/wiki/Custom-rendering-gems#changing-the-commonmarker-rendering-options

**Comment by jstolarek** [comment]
Thanks for updating the wiki, but I'm still having some issues with this. Firstly, there seems to be a typo on the wiki: `... => proc ...` should read `... = proc` I think. If I fix that then nothing renders on my wiki and every page just displays an error "Failed to render page: option ':FOOTNOTES' does not exist for CommonMarker::Config::Render". I placed the code snippet at the top level of my `config.rb` - should this be done differently, e.g. by putting it inside a module and/or a class?

**Comment by dometto** [comment]
@jstolarek check whether it works with another option, e.g. `:HARDBREAKS`? For me it does. If it's just `:FOOTNOTES` that gives you trouble, this looks like a bug in `commonmarker` rather than in gollum's approach.

I've updated the wiki!

**Comment by jstolarek** [comment]
Apparently all the rendering options work, but none of the parsing options do. I'm guessing this is related to how [this](https://github.com/gjtorikian/commonmarker/blob/fc1d7c093c4b8c45a665183e5aefa6a497cc15f3/lib/commonmarker.rb) `commonmarker` file handles options?

**Comment by dometto** [comment]
That seems right. You can try playing around with using `render_doc` (and then converting the resulting document to HTML) in the code snippet. Feel free to update the wiki with more examples.

**Comment by jstolarek** [comment]
Ok, I figured it out and updated the wiki. To enable a parsing option you need to say:

```
CommonMarker.render_doc(content, [:FOOTNOTES]).to_html
```

I still don't see how to change both rendering and parsing options at the same time, say, if I want to enable `:FOOTNOTES` and `:HARDBREAKS`. This seems to be a limitation on `commonmarker` side though.

**Comment by jstolarek** [comment]
Got it:

```
CommonMarker.render_doc(content, [:FOOTNOTES]).to_html([:HARDBREAKS])
```

I'll update the wiki.
